### ISSUE TITLE
install_magma failed when creating the Pytorch base image in CentOS7

### ISSUE THREAD

**Issue by WBobby** [ROCm/pytorch#820]
## To Reproduce

1. Enter .circle/docker folder
2. Run ./build.sh pytorch-devtoolset7-centos7.5.1804-rocm3.5.1-py3.6
3. The build will failed when running the install_magma function of the install_rocm.sh

sparse_hip/src/magma_zqr_wrapper.cpp  sparse_hip/src/magma_zcustomspmv.cpp sparse_hip/src/magma_zcustomprecond.cpp  sparse_hip/src/magma_z_precond_wrapper.cpp sparse_hip/src/magma_z_solver_wrapper.cpp sparse_hip/src/zresidual.cpp sparse_hip/src/zresidualvec.cpp  sparse_hip/src/zjacobidomainoverlap.cpp          >> Makefile.gen
[2021-04-26T15:49:34.473Z] Traceback (most recent call last):
[2021-04-26T15:49:34.473Z]   File "./tools/codegen.py", line 360, in <module>
[2021-04-26T15:49:34.473Z]     main()
[2021-04-26T15:49:34.473Z]   File "./tools/codegen.py", line 322, in main
[2021-04-26T15:49:34.473Z]     src = SourceFile( filename )
[2021-04-26T15:49:34.473Z]   File "./tools/codegen.py", line 171, in __init__
[2021-04-26T15:49:34.473Z]     self._text = fd.read()
[2021-04-26T15:49:34.473Z]   File "/opt/conda/lib/python3.6/encodings/ascii.py", line 26, in decode
[2021-04-26T15:49:34.473Z]     return codecs.ascii_decode(input, self.errors)[0]
[2021-04-26T15:49:34.473Z] UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 21255: ordinal not in range(128)
[2021-04-26T15:49:34.473Z] make: *** Deleting file 'Makefile.gen'
[2021-04-26T15:49:34.473Z] ===== shared library lib/libmagma.so

## Expected behavior

Two reason cause it failed:
1. There are some Non ASCII code in the source code of the magma
2. Cannot set LC_ALL="en_US.UTF-8" LC_CTYPE="en_US.UTF-8"

After above two point fixed, install_magma passed.

**Comment by amathews-amd** [comment]
https://bitbucket.org/icl/magma/pull-requests/10

**Comment by ppanchad-amd** [comment]
@WBobby Has your issue been resolved? If so, please close the ticket. Thanks!
